// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBook'](arg1, arg2, arg3);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DeleteImage(arg1, arg2) {
  return window['go']['main']['App']['DeleteImage'](arg1, arg2);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function GetImagesInBook(arg1) {
  return window['go']['main']['App']['GetImagesInBook'](arg1);
}

export function HasPassword() {
  return window['go']['main']['App']['HasPassword']();
}

export function RenameBook(arg1, arg2) {
  return window['go']['main']['App']['RenameBook'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetBookCover(arg1, arg2) {
  return window['go']['main']['App']['SetBookCover'](arg1, arg2);
}

export function SetMasterPassword(arg1) {
  return window['go']['main']['App']['SetMasterPassword'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
