// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBook(arg1:string,arg2:string):Promise<string>;

export function GetBooks():Promise<Array<main.Book>>;

export function GetImagesInBook(arg1:string):Promise<Array<string>>;

export function HasPassword():Promise<boolean>;

export function SelectFolder():Promise<string>;

export function SetMasterPassword(arg1:string):Promise<boolean>;

export function VerifyPassword(arg1:string):Promise<boolean>;
