// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchImportBooks(arg1) {
  return window['go']['main']['App']['BatchImportBooks'](arg1);
}

export function CreateBook(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBook'](arg1, arg2, arg3);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DeleteImage(arg1, arg2) {
  return window['go']['main']['App']['DeleteImage'](arg1, arg2);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function GetChapters(arg1) {
  return window['go']['main']['App']['GetChapters'](arg1);
}

export function GetImagesInChapter(arg1, arg2) {
  return window['go']['main']['App']['GetImagesInChapter'](arg1, arg2);
}

export function HasHiddenZonePassword() {
  return window['go']['main']['App']['HasHiddenZonePassword']();
}

export function HasPassword() {
  return window['go']['main']['App']['HasPassword']();
}

export function IsHiddenZoneActive() {
  return window['go']['main']['App']['IsHiddenZoneActive']();
}

export function LockBook(arg1, arg2) {
  return window['go']['main']['App']['LockBook'](arg1, arg2);
}

export function LockHiddenZone() {
  return window['go']['main']['App']['LockHiddenZone']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetBookCover(arg1, arg2) {
  return window['go']['main']['App']['SetBookCover'](arg1, arg2);
}

export function SetHiddenZonePassword(arg1) {
  return window['go']['main']['App']['SetHiddenZonePassword'](arg1);
}

export function SetMasterPassword(arg1) {
  return window['go']['main']['App']['SetMasterPassword'](arg1);
}

export function ToggleHiddenZone(arg1) {
  return window['go']['main']['App']['ToggleHiddenZone'](arg1);
}

export function UnlockBook(arg1) {
  return window['go']['main']['App']['UnlockBook'](arg1);
}

export function UpdateBookMetadata(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateBookMetadata'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateBookProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateBookProgress'](arg1, arg2);
}

export function VerifyBookPassword(arg1, arg2) {
  return window['go']['main']['App']['VerifyBookPassword'](arg1, arg2);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
